apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: {{ .Release.Name }}-service-prod
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-cluster-issuer
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Release.Name }}-tls-secret
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /sync/(.*)
        backend:
          serviceName: {{ .Release.Name }}-service-prod
          servicePort: {{ .Values.service.port }}
