apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.userIdentityId }}
    keyvaultName: {{ .Values.keyVault.keyVaultName }}
    objects: |
      array:
        - |
          objectName: ai-key
          objectType: secret
        - |
          objectName: redis-backplane
          objectType: secret
        - |
          objectName: redis-cache
          objectType: secret
    resourceGroup: {{ .Values.keyVault.resourceGroup }}
    subscriptionId: {{ .Values.keyVault.subscriptionId }}
    tenantId: {{ .Values.keyVault.tenantId }}
  secretObjects:
  - secretName: ai-key
    type: Opaque
    data:
    - objectName: ai-key
      key: key
  - secretName: redis-backplane
    type: Opaque
    data:
    - objectName: redis-backplane
      key: redis-password
  - secretName: redis-cache
    type: Opaque
    data:
    - objectName: redis-cache
      key: redis-password
